export const SELECTORS = {
  // Auth
  login: {
    emailInput: '[data-testid="login-email-input"]',
    passwordInput: '[data-testid="login-password-input"]',
    submitButton: '[data-testid="login-submit-button"]',
    errorMessage: '[data-testid="login-error-message"]',
    googleButton: '[data-testid="login-google-button"]',
    registerLink: '[data-testid="login-register-link"]',
  },
  register: {
    nameInput: '[data-testid="register-name-input"]',
    emailInput: '[data-testid="register-email-input"]',
    passwordInput: '[data-testid="register-password-input"]',
    confirmInput: '[data-testid="register-confirm-input"]',
    submitButton: '[data-testid="register-submit-button"]',
  },
  // Navbar
  navbar: {
    logo: '[data-testid="navbar-logo"]',
    searchInput: '[data-testid="navbar-search-input"]',
    loginLink: '[data-testid="navbar-login-link"]',
    userMenu: '[data-testid="navbar-user-menu"]',
    logoutButton: '[data-testid="navbar-logout-button"]',
    mobileToggle: '[data-testid="navbar-mobile-toggle"]',
    createListingButton: '[data-testid="navbar-create-listing"]',
  },
  // Listings
  listings: {
    searchInput: '[data-testid="listings-search-input"]',
    categorySelect: '[data-testid="listings-category-select"]',
    citySelect: '[data-testid="listings-city-select"]',
    priceMin: '[data-testid="listings-price-min"]',
    priceMax: '[data-testid="listings-price-max"]',
    card: '[data-testid="listing-card"]',
    cardTitle: '[data-testid="listing-card-title"]',
    cardPrice: '[data-testid="listing-card-price"]',
    cardLocation: '[data-testid="listing-card-location"]',
    cardImage: '[data-testid="listing-card-image"]',
    loadingSkeleton: '[data-testid="listings-loading-skeleton"]',
    emptyState: '[data-testid="listings-empty-state"]',
    pagination: '[data-testid="listings-pagination"]',
  },
  // Listing Detail
  listingDetail: {
    title: '[data-testid="listing-detail-title"]',
    description: '[data-testid="listing-detail-description"]',
    price: '[data-testid="listing-detail-price"]',
    category: '[data-testid="listing-detail-category"]',
    location: '[data-testid="listing-detail-location"]',
    gallery: '[data-testid="listing-detail-gallery"]',
    contactSeller: '[data-testid="listing-contact-seller"]',
    favoriteButton: '[data-testid="listing-favorite-button"]',
    editButton: '[data-testid="listing-edit-button"]',
    deleteButton: '[data-testid="listing-delete-button"]',
  },
  // Create Listing
  createListing: {
    titleInput: '[data-testid="create-listing-title"]',
    descriptionInput: '[data-testid="create-listing-description"]',
    priceInput: '[data-testid="create-listing-price"]',
    categorySelect: '[data-testid="create-listing-category"]',
    cityInput: '[data-testid="create-listing-city"]',
    stateInput: '[data-testid="create-listing-state"]',
    imageUpload: '[data-testid="create-listing-image-upload"]',
    imagePreview: '[data-testid="create-listing-image-preview"]',
    submitButton: '[data-testid="create-listing-submit"]',
    errorMessage: '[data-testid="create-listing-error"]',
  },
  // Chat
  chat: {
    conversationList: '[data-testid="chat-conversation-list"]',
    conversationItem: '[data-testid="chat-conversation-item"]',
    conversationSearch: '[data-testid="chat-conversation-search"]',
    messageArea: '[data-testid="chat-message-area"]',
    messageBubble: '[data-testid="chat-message-bubble"]',
    messageInput: '[data-testid="chat-message-input"]',
    sendButton: '[data-testid="chat-send-button"]',
    attachmentButton: '[data-testid="chat-attachment-button"]',
    typingIndicator: '[data-testid="chat-typing-indicator"]',
    unreadBadge: '[data-testid="chat-unread-badge"]',
    dateSeparator: '[data-testid="chat-date-separator"]',
    connectionBanner: '[data-testid="chat-connection-banner"]',
    emptyState: '[data-testid="chat-empty-state"]',
    loadingSkeleton: '[data-testid="chat-loading-skeleton"]',
  },
  // Profile
  profile: {
    nameInput: '[data-testid="profile-name-input"]',
    bioInput: '[data-testid="profile-bio-input"]',
    avatar: '[data-testid="profile-avatar"]',
    avatarUpload: '[data-testid="profile-avatar-upload"]',
    saveButton: '[data-testid="profile-save-button"]',
    myListingsTab: '[data-testid="profile-my-listings-tab"]',
    favoritesTab: '[data-testid="profile-favorites-tab"]',
  },
  // Admin
  admin: {
    usersTable: '[data-testid="admin-users-table"]',
    banUserButton: '[data-testid="admin-ban-user-button"]',
    listingsTable: '[data-testid="admin-listings-table"]',
    approveListingButton: '[data-testid="admin-approve-listing"]',
    rejectListingButton: '[data-testid="admin-reject-listing"]',
    dashboardStats: '[data-testid="admin-dashboard-stats"]',
  },
  // Common
  common: {
    toast: '[data-testid="toast-notification"]',
    modal: '[data-testid="modal-dialog"]',
    modalConfirm: '[data-testid="modal-confirm-button"]',
    modalCancel: '[data-testid="modal-cancel-button"]',
    loadingSpinner: '[data-testid="loading-spinner"]',
    errorBoundary: '[data-testid="error-boundary"]',
  },
} as const;
