import type { ResponseSection, SuggestedAction } from '../services/responseTypes'
import type { IntentClassification } from '../types'

export interface SearchArticleMetadata {
  owner: string
  version: string
  lastReviewed: string
}

export interface SearchArticle {
  id: string
  version: number
  title: string
  intent: 'SEARCH_LISTINGS'
  category: string
  triggers: string[]
  response: ResponseSection[]
  actions: SuggestedAction[]
  metadata: SearchArticleMetadata
  isDefault?: boolean
  lastUpdated: string
}

const LAST_UPDATED = '2026-07-11'
const VERSION = 1
const META: SearchArticleMetadata = {
  owner: 'ValBot Knowledge Base',
  version: '1.0',
  lastReviewed: '2026-07-11',
}

const SEARCH_ACTIONS: SuggestedAction[] = [
  { label: 'Compare Items', value: 'compare' },
  { label: 'Refine Search', value: 'refine search' },
  { label: 'Contact Seller', value: 'contact seller' },
  { label: 'Save Search', value: 'save search' },
]

const articles: SearchArticle[] = [
  // ───────────────────────── VEHICLE SEARCH (25) ─────────────────────────
  {
    id: 'SEA-VEH-001',
    version: VERSION,
    title: 'Searching for Cars',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['car', 'cars', 'automobile'],
    isDefault: true,
    response: [
      { type: 'text', content: 'You can narrow car listings on ValClassifieds by budget, city, fuel type, and condition. Browse the results and contact any seller directly to learn more.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-002',
    version: VERSION,
    title: 'Searching for Bikes and Scooters',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['bike', 'bikes', 'scooter', 'motorcycle', 'motorbike'],
    response: [
      { type: 'text', content: 'Find two-wheelers by brand, budget, and city on ValClassifieds. Use filters to compare listings and reach out to verified sellers.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-003',
    version: VERSION,
    title: 'Searching for Used Cars',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['used car', 'second hand', 'pre owned'],
    response: [
      { type: 'text', content: 'Used car listings can be filtered by kilometre reading, year, and ownership. Always check the photos and ask the seller for the service record.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-004',
    version: VERSION,
    title: 'Searching for New Cars',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['new car', 'showroom car'],
    response: [
      { type: 'text', content: 'Browse new and demo cars on ValClassifieds, and filter by model, fuel, and city to shortlist the right vehicle.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-005',
    version: VERSION,
    title: 'Searching for Electric Vehicles',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['ev', 'electric car', 'electric vehicle'],
    response: [
      { type: 'text', content: 'Filter electric vehicles by range, battery, and charging type. Compare listings and message sellers for more details.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-006',
    version: VERSION,
    title: 'Searching for SUVs',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['suv'],
    response: [
      { type: 'text', content: 'SUVs can be filtered by seating, fuel, and budget. Browse the results and contact sellers to confirm availability.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-007',
    version: VERSION,
    title: 'Searching for Luxury Cars',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['luxury car', 'premium car'],
    response: [
      { type: 'text', content: 'Refine luxury car listings by brand, model, and year. Review the photos and service history before you connect with a seller.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-008',
    version: VERSION,
    title: 'Searching for Commercial Vehicles',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['commercial vehicle', 'truck', 'tempo', 'van'],
    response: [
      { type: 'text', content: 'Find tempos, trucks, and vans by load capacity and city. Filter results and message the seller for documents and condition.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-009',
    version: VERSION,
    title: 'Searching Vehicles by Budget',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['budget', 'under', 'price range', 'lakh', 'within'],
    response: [
      { type: 'text', content: 'Set a maximum budget to see only vehicles you can afford. Widening the range slightly can reveal more options nearby.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-010',
    version: VERSION,
    title: 'Searching Vehicles by City',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['city', 'location', 'near me', 'nearby'],
    response: [
      { type: 'text', content: 'Add your city to see vehicles available locally. Local results make inspection and pickup much easier.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-011',
    version: VERSION,
    title: 'Searching Vehicles by Brand',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['brand', 'maruti', 'hyundai', 'tata', 'mahindra', 'toyota', 'honda'],
    response: [
      { type: 'text', content: 'Filter by brand and model to compare similar vehicles. This helps you spot the right variant and fair price.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-012',
    version: VERSION,
    title: 'Searching Vehicles by Fuel Type',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['fuel', 'petrol', 'diesel', 'cng'],
    response: [
      { type: 'text', content: 'Choose petrol, diesel, or CNG to match your running needs. Combine with budget for sharper results.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-013',
    version: VERSION,
    title: 'Searching Vehicles by Condition',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['condition', 'certified'],
    response: [
      { type: 'text', content: 'Filter by new, used, or certified pre-owned to match your budget and peace of mind.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-014',
    version: VERSION,
    title: 'Searching Automatic Vehicles',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['automatic', 'gear'],
    response: [
      { type: 'text', content: 'Looking for automatic? Filter by transmission to see only matching listings, then contact the seller to confirm.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-015',
    version: VERSION,
    title: 'Searching Vehicles by Mileage',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['mileage', 'km'],
    response: [
      { type: 'text', content: 'Lower kilometre readings usually mean less wear. Use filters and compare similar models to judge value.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-016',
    version: VERSION,
    title: 'Searching Verified Vehicle Sellers',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['verified', 'verified seller'],
    response: [
      { type: 'text', content: 'Prefer verified sellers for added confidence. You can still ask for the RC, insurance, and service record before deciding.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-017',
    version: VERSION,
    title: 'Searching Vehicles with Photos',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['photo', 'photos', 'with photos'],
    response: [
      { type: 'text', content: 'Listings with clear photos show condition honestly. Filter for photo-rich results to save time.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-018',
    version: VERSION,
    title: 'Searching Latest Vehicle Listings',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['latest', 'newest', 'recent'],
    response: [
      { type: 'text', content: 'Sort by newest to see fresh vehicle listings first. New posts often get quick responses from buyers.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-019',
    version: VERSION,
    title: 'Searching Cheapest Vehicles',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['cheap', 'cheapest', 'low price'],
    response: [
      { type: 'text', content: 'Sort by price low to high to find the most affordable vehicles. Always verify condition before you commit.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-020',
    version: VERSION,
    title: 'Searching a Specific Model',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['model', 'variant'],
    response: [
      { type: 'text', content: 'Search the exact model or variant to compare prices across sellers in your city.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-021',
    version: VERSION,
    title: 'Searching a Family Car',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['family', 'family car'],
    response: [
      { type: 'text', content: 'For family use, filter by seating, safety, and boot space. Compare a few listings before shortlisting.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-022',
    version: VERSION,
    title: 'Searching for Bicycles',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['bicycle', 'cycle'],
    response: [
      { type: 'text', content: 'Find bicycles by type and budget. Check the frame size and condition in the photos before contacting the seller.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-023',
    version: VERSION,
    title: 'Vehicle Finance and Loan Search',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['finance', 'loan', 'emi'],
    response: [
      { type: 'text', content: 'Many vehicle listings work with financing. Filter by budget you can afford monthly, then discuss loan options with the seller.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-024',
    version: VERSION,
    title: 'Searching by Transmission',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['transmission', 'manual'],
    response: [
      { type: 'text', content: 'Filter by manual or automatic transmission to match your driving preference.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-VEH-025',
    version: VERSION,
    title: 'Searching Vehicles Near Me',
    intent: 'SEARCH_LISTINGS',
    category: 'vehicles',
    triggers: ['near me', 'around me', 'my area'],
    response: [
      { type: 'text', content: 'Set your location to see vehicles near you. Nearby results make test drives and handover simpler.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  // ───────────────────────── PROPERTY SEARCH (20) ─────────────────────────
  {
    id: 'SEA-PRO-001',
    version: VERSION,
    title: 'Searching for Houses',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['house', 'houses', 'independent house'],
    isDefault: true,
    response: [
      { type: 'text', content: 'Refine house listings by budget, locality, and BHK on ValClassifieds. Review photos and documents, then contact the owner or agent.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-002',
    version: VERSION,
    title: 'Searching for Apartments and Flats',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['apartment', 'flat'],
    response: [
      { type: 'text', content: 'Filter flats by BHK, furnishing, and society. Compare listings in your preferred locality to find the right home.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-003',
    version: VERSION,
    title: 'Searching for Villas and Bungalows',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['villa', 'bungalow'],
    response: [
      { type: 'text', content: 'Browse villas and bungalows by locality and price. Check amenities and approvals before connecting with the seller.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-004',
    version: VERSION,
    title: 'Searching for Land and Plots',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['land', 'plot', 'site'],
    response: [
      { type: 'text', content: 'Find plots by location and size. Always verify the title and approvals through the listing before proceeding.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-005',
    version: VERSION,
    title: 'Searching for Commercial Property',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['office', 'shop', 'commercial'],
    response: [
      { type: 'text', content: 'Filter commercial spaces by type and locality. Compare options and message the lister for lease or sale terms.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-006',
    version: VERSION,
    title: 'Searching for Rentals',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['rent', 'rental', 'lease'],
    response: [
      { type: 'text', content: 'Set your budget and locality to see rental homes. Confirm deposit and notice period with the owner directly.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-007',
    version: VERSION,
    title: 'Searching Property by Budget',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['budget', 'under', 'price range', 'crore', 'lakh'],
    response: [
      { type: 'text', content: 'Use a budget filter to see properties within your range. A small adjustment can reveal more suitable homes.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-008',
    version: VERSION,
    title: 'Searching Property by Locality',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['locality', 'city', 'location', 'near me'],
    response: [
      { type: 'text', content: 'Add your locality to see homes nearby. Local listings make visits and paperwork easier.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-009',
    version: VERSION,
    title: 'Searching by BHK',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['bhk', 'bedroom', '1bhk', '2bhk', '3bhk'],
    response: [
      { type: 'text', content: 'Filter by BHK to match your space needs, then compare furnishing and floor level across listings.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-010',
    version: VERSION,
    title: 'Searching by Property Type',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['type', 'resale', 'new property'],
    response: [
      { type: 'text', content: 'Choose resale or new property to focus your search. Each has different approvals and timelines to check.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-011',
    version: VERSION,
    title: 'Searching Verified Property Listings',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['verified', 'verified seller'],
    response: [
      { type: 'text', content: 'Verified listings give added confidence. Still confirm the title and approvals with the owner before paying.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-012',
    version: VERSION,
    title: 'Searching Property with Photos',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['photo', 'photos'],
    response: [
      { type: 'text', content: 'Photo-rich listings show rooms and amenities clearly. Filter for them to shortlist faster.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-013',
    version: VERSION,
    title: 'Searching Latest Property Listings',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['latest', 'newest', 'recent'],
    response: [
      { type: 'text', content: 'Sort by newest to catch fresh property posts. New listings often get quick buyer interest.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-014',
    version: VERSION,
    title: 'Searching Cheapest Property',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['cheap', 'cheapest'],
    response: [
      { type: 'text', content: 'Sort by price low to high to find affordable homes. Verify documents and society dues before deciding.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-015',
    version: VERSION,
    title: 'Searching by Furnishing',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['furnished', 'unfurnished', 'semi furnished'],
    response: [
      { type: 'text', content: 'Filter furnished, semi-furnished, or unfurnished to match your move-in plan.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-016',
    version: VERSION,
    title: 'Searching by Amenities',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['amenities', 'parking', 'gym', 'pool'],
    response: [
      { type: 'text', content: 'Filter by amenities like parking, gym, or power backup to find a home that fits your lifestyle.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-017',
    version: VERSION,
    title: 'Searching by Possession',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['possession', 'ready', 'under construction'],
    response: [
      { type: 'text', content: 'Choose ready-to-move or under-construction based on your timeline. Check the completion status before you proceed.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-018',
    version: VERSION,
    title: 'Searching Property Near Me',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['near me', 'around me'],
    response: [
      { type: 'text', content: 'Set your location to see homes near you. Nearby options simplify visits and paperwork.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-019',
    version: VERSION,
    title: 'Searching by Area and Sqft',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['sqft', 'area', 'sq ft'],
    response: [
      { type: 'text', content: 'Filter by carpet or built-up area to match your space needs, then compare prices per square foot.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PRO-020',
    version: VERSION,
    title: 'Searching by Facing and Floor',
    intent: 'SEARCH_LISTINGS',
    category: 'property',
    triggers: ['facing', 'floor', 'east', 'west'],
    response: [
      { type: 'text', content: 'Filter by facing and floor level to match preference and light. Compare similar units before deciding.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },

  // ───────────────────────── ELECTRONICS SEARCH (20) ─────────────────────────
  {
    id: 'SEA-ELE-001',
    version: VERSION,
    title: 'Searching for Phones',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['phone', 'phones', 'mobile', 'smartphone'],
    isDefault: true,
    response: [
      { type: 'text', content: 'Filter phones by brand, budget, and condition on ValClassifieds. Check the IMEI and photos, then message the seller.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-002',
    version: VERSION,
    title: 'Searching for Laptops',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['laptop', 'computer', 'macbook'],
    response: [
      { type: 'text', content: 'Narrow laptops by RAM, storage, and budget. Compare listings and ask for the bill and battery health.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-003',
    version: VERSION,
    title: 'Searching for Gaming Laptops',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['gaming laptop', 'gaming'],
    response: [
      { type: 'text', content: 'Filter gaming laptops by graphics, RAM, and budget to find the right performance for your needs.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-004',
    version: VERSION,
    title: 'Searching for TVs and Monitors',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['tv', 'television', 'monitor'],
    response: [
      { type: 'text', content: 'Find TVs and monitors by size and condition. Review photos for screen quality before contacting the seller.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-005',
    version: VERSION,
    title: 'Searching for Cameras',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['camera', 'dslr'],
    response: [
      { type: 'text', content: 'Filter cameras by type and budget. Ask the seller for sample images and shutter count.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-006',
    version: VERSION,
    title: 'Searching for Audio Gear',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['headphones', 'earbuds', 'speaker'],
    response: [
      { type: 'text', content: 'Browse headphones, earbuds, and speakers by brand and condition. Confirm pairing status before buying.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-007',
    version: VERSION,
    title: 'Searching for Consoles',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['console', 'playstation', 'xbox', 'ps5'],
    response: [
      { type: 'text', content: 'Find consoles by model and condition. Confirm accounts are removed and accessories are included.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-008',
    version: VERSION,
    title: 'Searching Electronics by Budget',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['budget', 'under', 'price range'],
    response: [
      { type: 'text', content: 'Set a budget to see electronics you can afford. A small increase can unlock better condition or specs.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-009',
    version: VERSION,
    title: 'Searching Electronics by Brand',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['brand', 'samsung', 'apple', 'xiaomi', 'sony'],
    response: [
      { type: 'text', content: 'Filter by brand to compare the same model across sellers and spot the best price.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-010',
    version: VERSION,
    title: 'Searching Electronics by Condition',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['condition', 'refurbished'],
    response: [
      { type: 'text', content: 'Filter by new, used, or refurbished to match your budget. Check warranty and photos before deciding.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-011',
    version: VERSION,
    title: 'Searching with Warranty',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['warranty', 'bill', 'invoice'],
    response: [
      { type: 'text', content: 'Filter for items with a valid bill and warranty for extra peace of mind. Confirm transferability with the seller.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-012',
    version: VERSION,
    title: 'Searching Electronics with Photos',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['photo', 'photos'],
    response: [
      { type: 'text', content: 'Photo-rich listings show real condition. Filter for them to avoid surprises.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-013',
    version: VERSION,
    title: 'Searching Latest Electronics',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['latest', 'newest', 'recent'],
    response: [
      { type: 'text', content: 'Sort by newest to see freshly listed electronics first.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-014',
    version: VERSION,
    title: 'Searching Cheapest Electronics',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['cheap', 'cheapest'],
    response: [
      { type: 'text', content: 'Sort by price low to high to find budget electronics. Verify condition and warranty before buying.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-015',
    version: VERSION,
    title: 'Searching by Storage',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['storage', '256gb', '512gb', '1tb'],
    response: [
      { type: 'text', content: 'Filter by storage to match your needs, then compare prices for the same capacity.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-016',
    version: VERSION,
    title: 'Searching by RAM',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['ram', '8gb', '16gb'],
    response: [
      { type: 'text', content: 'Filter laptops and tablets by RAM for the performance you need.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-017',
    version: VERSION,
    title: 'Searching Verified Sellers',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['verified', 'verified seller'],
    response: [
      { type: 'text', content: 'Prefer verified sellers for electronics. Still confirm IMEI or serial and condition.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-018',
    version: VERSION,
    title: 'Searching Electronics Near Me',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['near me', 'around me'],
    response: [
      { type: 'text', content: 'Add your location to see electronics nearby for easy pickup or handover.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-019',
    version: VERSION,
    title: 'Searching for Tablets',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['tablet', 'ipad'],
    response: [
      { type: 'text', content: 'Find tablets by size and condition. Confirm the account is removed before you buy.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-ELE-020',
    version: VERSION,
    title: 'Searching for Home Appliances',
    intent: 'SEARCH_LISTINGS',
    category: 'electronics',
    triggers: ['appliance', 'fridge', 'washing machine', 'microwave'],
    response: [
      { type: 'text', content: 'Browse appliances by type and condition. Ask about age and any installation needs before purchasing.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  // ───────────────────────── FURNITURE & HOME SEARCH (12) ─────────────────────────
  {
    id: 'SEA-FUR-001',
    version: VERSION,
    title: 'Searching for Furniture',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['furniture', 'home'],
    isDefault: true,
    response: [
      { type: 'text', content: 'Filter furniture by type, condition, and location on ValClassifieds. Check dimensions and photos before arranging pickup.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-002',
    version: VERSION,
    title: 'Searching for Sofas',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['sofa', 'couch'],
    response: [
      { type: 'text', content: 'Find sofas by size and condition. Confirm dimensions fit your space and review the photos closely.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-003',
    version: VERSION,
    title: 'Searching for Beds and Mattresses',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['bed', 'mattress'],
    response: [
      { type: 'text', content: 'Filter beds and mattresses by size and condition. Check for cleanliness before you decide.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-004',
    version: VERSION,
    title: 'Searching for Tables and Chairs',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['table', 'chair', 'desk'],
    response: [
      { type: 'text', content: 'Browse tables, chairs, and desks by material and condition. Confirm dimensions for your room.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-005',
    version: VERSION,
    title: 'Searching for Storage Furniture',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['wardrobe', 'cabinet', 'shelf'],
    response: [
      { type: 'text', content: 'Find wardrobes, cabinets, and shelves by size and condition. Check that doors and fittings work.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-006',
    version: VERSION,
    title: 'Searching for Home Decor',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['decor', 'curtain', 'carpet'],
    response: [
      { type: 'text', content: 'Browse decor by type and size. Review photos for condition and colour before buying.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-007',
    version: VERSION,
    title: 'Searching Furniture by Budget',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['budget', 'under', 'price range'],
    response: [
      { type: 'text', content: 'Set a budget to see furniture you can afford. Slightly widening it can reveal better-condition pieces.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-008',
    version: VERSION,
    title: 'Searching Furniture by Condition',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['condition', 'new', 'used'],
    response: [
      { type: 'text', content: 'Filter by new or used to match your budget. Inspect photos for wear before arranging pickup.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-009',
    version: VERSION,
    title: 'Searching Furniture with Photos',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['photo', 'photos'],
    response: [
      { type: 'text', content: 'Photo-rich listings show real condition. Filter for them to avoid surprises on bulky items.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-010',
    version: VERSION,
    title: 'Searching Latest or Cheapest Furniture',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['latest', 'cheapest', 'newest'],
    response: [
      { type: 'text', content: 'Sort by newest or price low to high to find fresh or affordable furniture near you.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-011',
    version: VERSION,
    title: 'Searching Furniture Near Me',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['near me', 'around me'],
    response: [
      { type: 'text', content: 'Add your location to see furniture nearby, which makes moving large items much easier.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FUR-012',
    version: VERSION,
    title: 'Searching Verified Sellers',
    intent: 'SEARCH_LISTINGS',
    category: 'furniture-home',
    triggers: ['verified', 'verified seller'],
    response: [
      { type: 'text', content: 'Prefer verified sellers for bigger purchases. Still confirm condition and dimensions before paying.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },

  // ───────────────────────── FASHION & LIFESTYLE SEARCH (10) ─────────────────────────
  {
    id: 'SEA-FAS-001',
    version: VERSION,
    title: 'Searching for Fashion',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['fashion', 'clothing', 'apparel'],
    isDefault: true,
    response: [
      { type: 'text', content: 'Filter fashion by size, brand, and condition on ValClassifieds. Check photos and descriptions before buying.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FAS-002',
    version: VERSION,
    title: 'Searching for Shoes',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['shoes', 'sneakers', 'boots'],
    response: [
      { type: 'text', content: 'Find shoes by size and brand. Review photos of soles and insoles for condition.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FAS-003',
    version: VERSION,
    title: 'Searching for Watches',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['watch', 'smartwatch'],
    response: [
      { type: 'text', content: 'Browse watches by brand and condition. Confirm serial and bill for premium models.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FAS-004',
    version: VERSION,
    title: 'Searching for Bags',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['bag', 'backpack', 'handbag'],
    response: [
      { type: 'text', content: 'Find bags by type and brand. Check zippers and lining in the photos before purchasing.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FAS-005',
    version: VERSION,
    title: 'Searching for Jewelry',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['jewelry', 'jewellery'],
    response: [
      { type: 'text', content: 'Filter jewelry by type and purity. Confirm hallmark and bill for gold and silver.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FAS-006',
    version: VERSION,
    title: 'Searching Fashion by Brand',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['brand', 'nike', 'adidas', 'puma'],
    response: [
      { type: 'text', content: 'Filter by brand to compare the same item across sellers and spot the best price.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FAS-007',
    version: VERSION,
    title: 'Searching Fashion by Budget',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['budget', 'under', 'price range'],
    response: [
      { type: 'text', content: 'Set a budget to see fashion you can afford. A small increase can reveal better brands.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FAS-008',
    version: VERSION,
    title: 'Searching Fashion by Size',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['size', 'm', 'l', 'xl'],
    response: [
      { type: 'text', content: 'Filter by size to see items that fit. Check the description for exact measurements.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FAS-009',
    version: VERSION,
    title: 'Searching Fashion with Photos',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['photo', 'photos'],
    response: [
      { type: 'text', content: 'Photo-rich listings show true colour and condition. Filter for them to buy with confidence.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-FAS-010',
    version: VERSION,
    title: 'Searching Fashion Near Me',
    intent: 'SEARCH_LISTINGS',
    category: 'fashion-lifestyle',
    triggers: ['near me', 'around me'],
    response: [
      { type: 'text', content: 'Add your location to see fashion nearby for quick pickup or exchange.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },

  // ───────────────────────── PET SEARCH (8) ─────────────────────────
  {
    id: 'SEA-PET-001',
    version: VERSION,
    title: 'Searching for Pets',
    intent: 'SEARCH_LISTINGS',
    category: 'pets',
    triggers: ['pet', 'pets', 'dog', 'cat'],
    isDefault: true,
    response: [
      { type: 'text', content: 'Browse pets by type and location on ValClassifieds. Always meet the pet and check health records before deciding.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PET-002',
    version: VERSION,
    title: 'Searching for Dogs and Puppies',
    intent: 'SEARCH_LISTINGS',
    category: 'pets',
    triggers: ['dog', 'puppy'],
    response: [
      { type: 'text', content: 'Find dogs and puppies by breed and age. Confirm vaccination and meet the pet in person.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PET-003',
    version: VERSION,
    title: 'Searching for Cats and Kittens',
    intent: 'SEARCH_LISTINGS',
    category: 'pets',
    triggers: ['cat', 'kitten'],
    response: [
      { type: 'text', content: 'Browse cats and kittens by age and breed. Check temperament and health before bringing one home.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PET-004',
    version: VERSION,
    title: 'Searching for Pet Supplies',
    intent: 'SEARCH_LISTINGS',
    category: 'pets',
    triggers: ['pet food', 'pet supplies'],
    response: [
      { type: 'text', content: 'Find pet food and accessories by type. Prefer sealed packs and check expiry dates.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PET-005',
    version: VERSION,
    title: 'Searching Pets by Location',
    intent: 'SEARCH_LISTINGS',
    category: 'pets',
    triggers: ['location', 'near me', 'city'],
    response: [
      { type: 'text', content: 'Add your city to see pets nearby. Local meetings are safer for both you and the animal.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PET-006',
    version: VERSION,
    title: 'Searching Pets with Photos',
    intent: 'SEARCH_LISTINGS',
    category: 'pets',
    triggers: ['photo', 'photos'],
    response: [
      { type: 'text', content: 'Photo-rich pet listings show real condition and temperament. Filter for them to decide faster.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PET-007',
    version: VERSION,
    title: 'Searching Latest Pets',
    intent: 'SEARCH_LISTINGS',
    category: 'pets',
    triggers: ['latest', 'newest'],
    response: [
      { type: 'text', content: 'Sort by newest to see recently listed pets and rehoming posts first.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-PET-008',
    version: VERSION,
    title: 'Searching Pet Adoption',
    intent: 'SEARCH_LISTINGS',
    category: 'pets',
    triggers: ['adoption', 'free', 'rehoming'],
    response: [
      { type: 'text', content: 'Find adoption and rehoming posts by location. Always prioritise the animal’s welfare and verify the owner.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },

  // ───────────────────────── JOB SEARCH (10) ─────────────────────────
  {
    id: 'SEA-JOB-001',
    version: VERSION,
    title: 'Searching for Jobs',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['job', 'jobs', 'career', 'vacancy'],
    isDefault: true,
    response: [
      { type: 'text', content: 'Filter jobs by role, location, and type on ValClassifieds. Read the full description and apply through the platform.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-JOB-002',
    version: VERSION,
    title: 'Searching IT and Software Jobs',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['software', 'it job', 'developer', 'engineer'],
    response: [
      { type: 'text', content: 'Find IT and software roles by skill and city. Confirm salary and experience before applying.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-JOB-003',
    version: VERSION,
    title: 'Searching Full-time Jobs',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['full time', 'permanent'],
    response: [
      { type: 'text', content: 'Filter for full-time roles to see permanent opportunities near you.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-JOB-004',
    version: VERSION,
    title: 'Searching Part-time Jobs',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['part time'],
    response: [
      { type: 'text', content: 'Browse part-time roles by location and skill. Confirm hours and pay before applying.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-JOB-005',
    version: VERSION,
    title: 'Searching Internships',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['internship', 'intern'],
    response: [
      { type: 'text', content: 'Find internships by field and city. Check stipend and duration in the description.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-JOB-006',
    version: VERSION,
    title: 'Searching Freelance Work',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['freelance', 'contract'],
    response: [
      { type: 'text', content: 'Browse freelance and contract roles by skill. Agree on scope and rate before you start.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-JOB-007',
    version: VERSION,
    title: 'Searching Jobs by Location',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['location', 'bangalore', 'city', 'near me'],
    response: [
      { type: 'text', content: 'Add your city to see local jobs. Remote roles can be filtered separately where available.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-JOB-008',
    version: VERSION,
    title: 'Searching Jobs by Experience',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['experience', 'fresher', 'senior'],
    response: [
      { type: 'text', content: 'Filter by experience level to match your stage, from fresher to senior roles.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-JOB-009',
    version: VERSION,
    title: 'Searching Work From Home',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['work from home', 'remote', 'wfh'],
    response: [
      { type: 'text', content: 'Filter for work-from-home and remote roles. Verify the employer before sharing documents.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-JOB-010',
    version: VERSION,
    title: 'Searching Jobs with Company Details',
    intent: 'SEARCH_LISTINGS',
    category: 'jobs',
    triggers: ['photo', 'company'],
    response: [
      { type: 'text', content: 'Review listings with company details and logos. Research the employer before applying.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  // ───────────────────────── SERVICE SEARCH (8) ─────────────────────────
  {
    id: 'SEA-SER-001',
    version: VERSION,
    title: 'Searching for Services',
    intent: 'SEARCH_LISTINGS',
    category: 'services',
    triggers: ['service', 'services'],
    isDefault: true,
    response: [
      { type: 'text', content: 'Filter services by type and location on ValClassifieds. Review the provider’s details and past work before booking.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-SER-002',
    version: VERSION,
    title: 'Searching Home Services',
    intent: 'SEARCH_LISTINGS',
    category: 'services',
    triggers: ['plumber', 'electrician', 'cleaning', 'repair'],
    response: [
      { type: 'text', content: 'Find plumbers, electricians, and cleaners by location. Confirm pricing and visit charges before the job.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-SER-003',
    version: VERSION,
    title: 'Searching Tutors and Coaching',
    intent: 'SEARCH_LISTINGS',
    category: 'services',
    triggers: ['tutor', 'coaching', 'tuition'],
    response: [
      { type: 'text', content: 'Browse tutors and coaches by subject and location. Ask about experience and demo sessions.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-SER-004',
    version: VERSION,
    title: 'Searching Services by Location',
    intent: 'SEARCH_LISTINGS',
    category: 'services',
    triggers: ['location', 'near me', 'city'],
    response: [
      { type: 'text', content: 'Add your location to see service providers nearby for faster response and visits.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-SER-005',
    version: VERSION,
    title: 'Searching Top-rated Services',
    intent: 'SEARCH_LISTINGS',
    category: 'services',
    triggers: ['rating', 'top rated', 'verified'],
    response: [
      { type: 'text', content: 'Filter for verified or top-rated providers to choose trusted help. Read details before booking.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-SER-006',
    version: VERSION,
    title: 'Searching Photography and Event Services',
    intent: 'SEARCH_LISTINGS',
    category: 'services',
    triggers: ['photography', 'catering', 'event'],
    response: [
      { type: 'text', content: 'Find photographers, caterers, and event help by city. Review portfolios and past work before hiring.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-SER-007',
    version: VERSION,
    title: 'Searching Services with Photos',
    intent: 'SEARCH_LISTINGS',
    category: 'services',
    triggers: ['photo', 'photos'],
    response: [
      { type: 'text', content: 'Providers with photos and portfolios are easier to trust. Filter for them when shortlisting.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-SER-008',
    version: VERSION,
    title: 'Searching Latest Services',
    intent: 'SEARCH_LISTINGS',
    category: 'services',
    triggers: ['latest', 'newest'],
    response: [
      { type: 'text', content: 'Sort by newest to see recently added service providers in your area.' },
    ],
    actions: SEARCH_ACTIONS,
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },

  // ───────────────────────── SEARCH REFINEMENT (7) ─────────────────────────
  {
    id: 'SEA-REF-001',
    version: VERSION,
    title: 'No Results Found',
    intent: 'SEARCH_LISTINGS',
    category: 'refinement',
    triggers: ['no results', 'no result', 'nothing found', '0 results', 'found nothing'],
    isDefault: true,
    response: [
      { type: 'text', content: 'We couldn’t find exact matches for your search. Try removing a filter, widening your location, or adjusting your budget to see more listings.' },
    ],
    actions: [
      { label: 'Remove Filters', value: 'refine search' },
      { label: 'Expand Search', value: 'refine search' },
      { label: 'Browse Categories', value: 'show categories' },
    ],
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-REF-002',
    version: VERSION,
    title: 'Remove Filters',
    intent: 'SEARCH_LISTINGS',
    category: 'refinement',
    triggers: ['remove filter', 'remove filters', 'clear filter', 'clear filters', 'reset filter'],
    response: [
      { type: 'text', content: 'Clearing your filters shows the full set of listings. You can then reapply just the ones that matter to narrow down.' },
    ],
    actions: [
      { label: 'Search Again', value: 'search' },
      { label: 'Expand Search', value: 'refine search' },
      { label: 'Browse Categories', value: 'show categories' },
    ],
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-REF-003',
    version: VERSION,
    title: 'Expand Search',
    intent: 'SEARCH_LISTINGS',
    category: 'refinement',
    triggers: ['expand', 'expand search', 'broaden', 'widen'],
    response: [
      { type: 'text', content: 'Widening your search to nearby cities or a larger budget can reveal more options. Adjust one filter at a time to stay relevant.' },
    ],
    actions: [
      { label: 'Change Budget', value: 'refine search' },
      { label: 'Change Location', value: 'refine search' },
      { label: 'Search Again', value: 'search' },
    ],
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-REF-004',
    version: VERSION,
    title: 'Change Budget',
    intent: 'SEARCH_LISTINGS',
    category: 'refinement',
    triggers: ['change budget', 'adjust budget', 'budget', 'price range'],
    response: [
      { type: 'text', content: 'Adjusting your budget filter changes how many listings you see. A slightly higher maximum often includes better-condition items.' },
    ],
    actions: [
      { label: 'Remove Filters', value: 'refine search' },
      { label: 'Expand Search', value: 'refine search' },
      { label: 'Search Again', value: 'search' },
    ],
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-REF-005',
    version: VERSION,
    title: 'Change Location',
    intent: 'SEARCH_LISTINGS',
    category: 'refinement',
    triggers: ['change location', 'different city', 'location', 'near me'],
    response: [
      { type: 'text', content: 'Broadening your location to nearby cities can surface more listings. Local results remain easiest for inspection and pickup.' },
    ],
    actions: [
      { label: 'Remove Filters', value: 'refine search' },
      { label: 'Expand Search', value: 'refine search' },
      { label: 'Search Again', value: 'search' },
    ],
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-REF-006',
    version: VERSION,
    title: 'Sort Results',
    intent: 'SEARCH_LISTINGS',
    category: 'refinement',
    triggers: ['sort', 'sort by', 'newest', 'price low', 'price high'],
    response: [
      { type: 'text', content: 'Sorting helps you scan listings faster. Use newest first for fresh posts or price low to high for the best deals.' },
    ],
    actions: [
      { label: 'Price Low to High', value: 'refine search' },
      { label: 'Newest First', value: 'refine search' },
      { label: 'Refine Search', value: 'refine search' },
    ],
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
  {
    id: 'SEA-REF-007',
    version: VERSION,
    title: 'Search Tips',
    intent: 'SEARCH_LISTINGS',
    category: 'refinement',
    triggers: ['search tips', 'tips', 'how to search', 'help searching'],
    response: [
      { type: 'text', content: 'For better results, pick the right category, add your city, and set a realistic budget. Use clear keywords and check photos before contacting a seller.' },
    ],
    actions: [
      { label: 'Browse Categories', value: 'show categories' },
      { label: 'Refine Search', value: 'refine search' },
      { label: 'Contact Seller', value: 'contact seller' },
    ],
    metadata: META,
    lastUpdated: LAST_UPDATED,
  },
]

export default articles

const CATEGORY_ALIASES: Record<string, string> = {
  'mobiles-tablets': 'electronics',
}

function normalizeCategory(category?: string): string | undefined {
  if (!category) return undefined
  return CATEGORY_ALIASES[category] ?? category
}

function scoreTriggerMatch(query: string, trigger: string): number {
  const q = query.toLowerCase().trim()
  const t = trigger.toLowerCase().trim()
  if (!t) return 0
  if (q === t) return 3
  if (q.startsWith(t)) return 2
  if (q.includes(t)) return 1
  return 0
}

function matchArticles(pool: SearchArticle[], query: string): SearchArticle | null {
  let best: { article: SearchArticle; score: number } | null = null
  for (const article of pool) {
    for (const trigger of article.triggers) {
      const score = scoreTriggerMatch(query, trigger)
      if (score > 0 && (best === null || score > best.score)) {
        best = { article, score }
      }
    }
  }
  return best ? best.article : null
}

export type SearchScenario = 'result' | 'zero' | 'refinement' | 'error'

export function selectSearchArticle(
  classification: IntentClassification,
  scenario: SearchScenario = 'result'
): SearchArticle {
  const query = (classification.entities.query ?? '').toLowerCase().trim()
  const category = normalizeCategory(classification.entities.category)

  const refinementPool = articles.filter(a => a.category === 'refinement')
  const refinementMatch = matchArticles(refinementPool, query)
  const noResults = articles.find(a => a.id === 'SEA-REF-001')!
  const searchTips = articles.find(a => a.id === 'SEA-REF-007')!

  if (scenario === 'zero') return noResults
  if (scenario === 'error') return searchTips
  if (scenario === 'refinement' && refinementMatch) return refinementMatch

  if (refinementMatch) return refinementMatch

  const scoped = category ? articles.filter(a => a.category === category) : []
  const catMatch = matchArticles(scoped, query)
  if (catMatch) return catMatch
  const catDefault = scoped.find(a => a.isDefault)
  if (catDefault) return catDefault

  return articles.find(a => a.isDefault) ?? articles[0]
}
